---
title: "Queensland Shark Program 2021 Catches - Great Barrier Reef Marine Park"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: rows
    source_code: embed
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

my_packages <- c("tidyverse", "plotly", "flexdashboard", "lubridate", "leaflet", "htmltools") 
lapply(my_packages, require, character.only = TRUE)

catches2021 <- read.csv("gbrmp-catch-statistics-2021.csv")
```

About {.sidebar}
-------------------------------------
This dashboard provides summary statistics about the catches in the Queensland Shark program at the Great Barrier Reef Marine Park in 2021. Catch details include: species, date, area, location, fate and number. 

The data was obtained from [Queensland's Open Data Portal](https://www.data.qld.gov.au/dataset/qld-shark-control-program-catch-statistics-great-barrier-reef-marine-park).

Created by [Li X Tan](https://www.github.com/lixtan/). Last updated: 2022-04-18

Row
-----------------------------------------------------------------------
```{r total-calculations, include = FALSE}
total_catch <- nrow(catches2021)
commonwealth_catch <- nrow(catches2021[catches2021$Marine.Park == "Commonwealth",])
state_catch <- nrow(catches2021[catches2021$Marine.Park == "State",])
```

### Total catches in 2021
```{r total-catch-2021}
valueBox(value = paste0(total_catch), icon = "fa-ship")
```

### Catches in Commonwealth Marine Park
```{r commonwealth-catch-2021}
valueBox(value = paste0(commonwealth_catch), icon = "fa-arrows")
```

### Catches in State Marine Park
```{r state-catch-2021}
valueBox(value = paste0(state_catch), icon = "fa-arrows-alt")
```

Row {.tabset}
-----------------------------------------------------------------------
### Area & Location
```{r area, echo = FALSE, fig.keep='none'}
labs <- lapply(seq(nrow(catches2021)), function(i) {
  paste0( '<p>', catches2021[i, "Location"], ', ', 
          catches2021[i, "Area"], '</p><p>', 
          catches2021[i, "Common.Name"], '</p><p>',
          catches2021[i, "Date"], '</p>') 
})

catch_map <- leaflet(catches2021) %>% addProviderTiles(providers$CartoDB.Voyager) %>%
  addCircleMarkers(lng = ~lon, lat =~lat, clusterOptions = markerClusterOptions(), label = lapply(labs, htmltools::HTML))
catch_map
```

### Catches over 2021
```{r time-series}
catches2021$Date <- dmy(catches2021$Date)
count_catches <- catches2021 %>% count(Date, Area) %>% 
  group_by(Area, Date) %>%
  summarise(Value = sum(n)) %>%
  mutate(Value = cumsum(Value))

catches_time_series <- count_catches %>% ggplot(aes(x=Date, y=Value, group=Area, color=Area)) +
    geom_line(size = 1) +
    labs(y="Cumulative Number of Catches") +
    theme_minimal() +
    scale_color_brewer(palette = "Set2")
catches_time_series
ggplotly(catches_time_series, tooltip = c("x", "y", "group"))
```

```{r setup-charts, include=FALSE}
species_fate <- catches2021 %>% count(Common.Name, Fate)
species_fate_chart <- ggplot(species_fate, aes(x = fct_reorder(Common.Name,n), y = n, fill = Fate)) + 
  coord_flip() +
  geom_bar(stat = "identity") +
  labs(x = "Number of catches", y = "Fish species - common name") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2")
```

### Species & Fate
```{r fate, echo = FALSE}
ggplotly(species_fate_chart, tooltip = c("n", "Fate"))
```